import type { MetadataRoute } from "next";
import { env } from "@/lib/env";

/**
 * The web app manifest, served at `/manifest.webmanifest`.
 *
 * Two audiences read this file. Someone who taps "Add to home screen" in
 * Chrome gets an installed PWA from it, and Bubblewrap reads it when it
 * generates the Play Store package — the app name, the colours and the icons
 * in the listing all come from here, so this is the single place they are
 * defined. Changing a colour or an icon here changes the *website*
 * immediately, but the installed Android app keeps the old one until the
 * wrapper is rebuilt (`bubblewrap update && bubblewrap build`).
 *
 * Icons are generated by `node scripts/generate-icons.mjs`.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${env.appName} — see who can refer you`,
    short_name: env.appName,
    description:
      "Find openings, see exactly who inside the company is open to referring you, request a referral, and track it from request to hired.",

    // Signed-in users are redirected onward from here; everyone else gets the
    // landing page. Either way "/" is the honest entry point.
    start_url: "/",
    // Everything lives under the origin root. Narrowing the scope would push
    // in-app links out into a browser tab and break the installed feel.
    scope: "/",
    id: "/",

    display: "standalone",
    orientation: "portrait",

    // Matches the page background so the splash screen does not flash a
    // different colour before first paint.
    background_color: "#f8fafc",
    // The near-black ink used in the navbar and footer, and the same value
    // as the `themeColor` in the root layout's viewport export. Android
    // tints the status bar and the task switcher with it.
    theme_color: "#05060c",

    lang: "en-IN",
    dir: "ltr",
    categories: ["business", "productivity"],

    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      // Android masks these to whatever shape the launcher uses, so the glyph
      // is drawn well inside the centre 80% safe zone.
      {
        src: "/icons/icon-maskable-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
      // Themed icons on Android 13+: only the alpha channel is used, the
      // launcher supplies the colour.
      {
        src: "/icons/icon-monochrome-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "monochrome",
      },
    ],

    // Long-press the installed icon to jump to the two screens people
    // actually reopen the app for.
    shortcuts: [
      {
        name: "My referrals",
        short_name: "Referrals",
        url: "/my-referrals",
        icons: [{ src: "/icons/icon-192.png", sizes: "192x192", type: "image/png" }],
      },
      {
        name: "Browse openings",
        short_name: "Openings",
        url: "/jobs",
        icons: [{ src: "/icons/icon-192.png", sizes: "192x192", type: "image/png" }],
      },
    ],

    // Once the app is on Play, Chrome offers the store listing rather than a
    // browser install — but only when it knows the package name.
    ...(env.android.packageName
      ? {
          related_applications: [
            {
              platform: "play",
              id: env.android.packageName,
              url: `https://play.google.com/store/apps/details?id=${env.android.packageName}`,
            },
          ],
          prefer_related_applications: true,
        }
      : {}),
  };
}
